var TTSV = {
    mssv: 20215408,
    ho_ten: "Nguyễn Trung Kiên",
    nam_vao_truong: "2021",
    bac_dao_tao: "Đại học đại trà",
    chuong_trinh: "Khoa học Máy tính 2021",
    khoa_vien_quan_ly: "Trường Công nghệ thông tin và Truyền thông",
    tinh_trang_hoc_tap: "Học",
    gioi_tinh: "Nam",
    lop: "Khoa học máy tính 04-K66",
    khoa_hoc: "66",
    email: "kien.nt215408@sis.hust.edu.vn",
    tong_ket_hoc_ky: "20231",
    trung_binh_tich_luy: "3.41",
    so_tc_no_dang_ky: "0",
    so_tc_tich_luy: "80",
    trinh_do_sinh_vien: "3",
    muc_canh_bao: "M0",
    dan_toc: "KINH",
    nam_tn_cap_3: "2021",
    dia_chi: "PHƯỜNG QUANG TRUNG, THÀNH PHỐ VINH, TỈNH NGHỆ AN",
    so_cmtnd: "040***07",
    noi_cap: "NGHỆ AN",
    ho_ten_bo: "NGUYỄN TRUNG HIẾU",
    nam_sinh_bo: "1974",
    nghe_nghiep_bo: "DOANH NGHIỆP",
    dien_thoai_bo: "093***89",
    email_bo: "TR*@*IL.COM",
    ton_giao: "KHÔNG",
    truong_thpt: "HUỲNH THÚC KHÁNG - NGHỆ AN",
    ho_khau: "PHƯỜNG QUANG TRUNG, THÀNH PHỐ VINH, TỈNH NGHỆ AN",
    so_dien_thoai: "093***31",
    ho_ten_me: "NGUYỄN THỊ TỐ NGA",
    nam_sinh_me: "1978",
    nghe_nghiep_me: "DOANH NGHIỆP",
    dien_thoai_me: "093***79",
    email_me: "KI*@*IL.COM"
};

const defaultTTSV = {
    mssv: 20215408,
    ho_ten: "Nguyễn Trung Kiên",
    nam_vao_truong: "2021",
    bac_dao_tao: "Đại học đại trà",
    chuong_trinh: "Khoa học Máy tính 2021",
    khoa_vien_quan_ly: "Trường Công nghệ thông tin và Truyền thông",
    tinh_trang_hoc_tap: "Học",
    gioi_tinh: "Nam",
    lop: "Khoa học máy tính 04-K66",
    khoa_hoc: "66",
    email: "kien.nt215408@sis.hust.edu.vn",
    tong_ket_hoc_ky: "20231",
    trung_binh_tich_luy: "3.41",
    so_tc_no_dang_ky: "0",
    so_tc_tich_luy: "80",
    trinh_do_sinh_vien: "3",
    muc_canh_bao: "M0",
    dan_toc: "KINH",
    nam_tn_cap_3: "2021",
    dia_chi: "PHƯỜNG QUANG TRUNG, THÀNH PHỐ VINH, TỈNH NGHỆ AN",
    so_cmtnd: "040***07",
    noi_cap: "NGHỆ AN",
    ho_ten_bo: "NGUYỄN TRUNG HIẾU",
    nam_sinh_bo: "1974",
    nghe_nghiep_bo: "DOANH NGHIỆP",
    dien_thoai_bo: "093***89",
    email_bo: "TR*@*IL.COM",
    ton_giao: "KHÔNG",
    truong_thpt: "HUỲNH THÚC KHÁNG - NGHỆ AN",
    ho_khau: "PHƯỜNG QUANG TRUNG, THÀNH PHỐ VINH, TỈNH NGHỆ AN",
    so_dien_thoai: "093***31",
    ho_ten_me: "NGUYỄN THỊ TỐ NGA",
    nam_sinh_me: "1978",
    nghe_nghiep_me: "DOANH NGHIỆP",
    dien_thoai_me: "093***79",
    email_me: "KI*@*IL.COM"
};